# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hampazly/helm-hello-world
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  internalPort: 80
  externalPort: 8080
  nodePort: 30100
