replicaCount: 1

image:
  repository: registry.synkzone.dev/lia/hello-world  # Uppdaterad till din Harbor registry
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# 🔥 **Använder en ConfigMap för att lagra statisk HTML**
persistence:
  enabled: true
  storageClass: "standard"  # Ändra om du har en specifik StorageClass
  accessMode: ReadWriteOnce
  size: 1Gi

volumes:
  - name: html-content
    configMap:
      name: "{{ include \"hello-world.fullname\" . }}-html"

volumeMounts:
  - name: html-content
    mountPath: "/usr/share/nginx/html"
    readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}